### ISSUE TITLE
Warnings when running in FastBoot

### ISSUE THREAD

**Issue by Windvis** [lblod/ember-rdfa-helpers#4]
When running an app which includes this addon with FastBoot the following warnings are shown:

```
DEPRECATION: Attempted to call store.adapterFor(), but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]
        at logDeprecationStackTrace (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:106:1)
        at HANDLERS.<computed> (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:26:1)
        at raiseOnDeprecation (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:133:1)
        at HANDLERS.<computed> (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:26:1)
        at invoke (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:38:1)
        at Object.deprecate (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:171:1)
        at assertDestroyedStore (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:9761:1)
        at Store.adapterFor (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:9360:1)
        at Store.findHasMany (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:8063:1)
        at Store._findHasManyByJsonApiResource (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:8086:1)
        at InternalModel.fetchAsyncHasMany (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:4388:1)
        at InternalModel.getHasMany (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:4412:1)
        at Mandataris.get (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/model/-private.js:515:1)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1881:1
        at untrack (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@glimmer/validator.js:794:1)
        at ComputedProperty.get (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1880:1)
        at Mandataris.CPGETTER_FUNCTION [as beleidsdomein] (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:988:1)
        at getPossibleMandatoryProxyValue (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1281:1)
        at _getProp (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1346:1)
        at _getPath (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1388:1)
        at get (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1332:1)
        at Class.get (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/mixins/observable.js:116:1)
        at Class.updatePropertyValue (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-rdfa-helpers/mixins/rdfa/standard.js:33:1)
        at sendEvent (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:219:1)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:480:1
        at Map.forEach (<anonymous>)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:476:1
        at Map.forEach (<anonymous>)
        at flushSyncObservers (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:474:1)
        at notifyPropertyChange (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:587:1)
        at Mandataris.notifyPropertyChange (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/mixins/observable.js:242:1)
        at InternalModel.notifyPropertyChange (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:4750:1)
        at RecordDataStoreWrapper.notifyPropertyChange (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:6746:1)
        at ManyRelationship.notifyManyArrayIsStale (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:1172:1)
        at ManyRelationship.inverseDidDematerialize (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:1025:1)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:314:1
        at Relationship.forAllMembers (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:328:1)
        at Relationship.recordDataDidDematerialize (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:302:1)
        at destroyRelationship (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:2101:1)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:1993:1
        at Array.forEach (<anonymous>)
        at RecordDataDefault._destroyRelationships (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:1991:1)
        at RecordDataDefault.unloadRecord (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/record-data/-private.js:1713:1)
        at InternalModel.dematerializeRecord (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:4151:1)
        at InternalModel.unloadRecord (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:4231:1)
        at InternalModelMap.clear (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:1633:1)
        at IdentityMap.clear (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:1687:1)
        at InternalModelFactory.clear (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:1963:1)
        at Store.unloadAll (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:8659:1)
        at Store.willDestroy (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:9616:1)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/system/core_object.js:202:1
        at invokeWithOnError (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/backburner.js:349:1)
        at Queue.flush (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/backburner.js:229:1)
        at DeferredActionQueues.flush (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/backburner.js:426:1)
        at Backburner._end (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/backburner.js:960:1)
        at Backburner._boundAutorunEnd (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/backburner.js:629:1)
        at run (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/vendor/babel-polyfill/polyfill.js:4536:1)
        at /tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/vendor/babel-polyfill/polyfill.js:4553:1
        at flush (/tmp/broccoli-41525lX81PBtfMRN/out-608-append_ember_auto_import_analyzer/assets/vendor/babel-polyfill/polyfill.js:1665:1)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Somewhere in that call stack `ember-rdfa-helpers/mixins/rdfa/standard.js:33:1` is mentioned, which points to thepropObserver and updatePropertyValue method.

**Comment by Windvis** [comment]
Possibly fixed by #7 since that removes the mixin and observers. Has to be tested though.
